name: Compile SCSS

on:
  push:
    branches:
      - main
    paths:
      - "scss/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS
        run: |
          mkdir -p distribution/css

          # Compile only SCSS files that are NOT partials
          for f in scss/*.scss; do
            filename=$(basename "$f")

            if [[ "$filename" != _* ]]; then
              name="${filename%.scss}"
              sass "$f" "distribution/css/$name.css" --no-source-map
            fi
          done

      - name: Commit compiled CSS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add distribution/css/*.css

          git commit -m "Auto-compile SCSS" || echo "No changes to commit"

          git pull https://x-access-token:${{ secrets.GH_PAT }}@github.com/Micharl13/Vector-front-end-framework.git main --rebase

          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Micharl13/Vector-front-end-framework.git HEAD:main
